context:
  name: garage
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://git.deuxfleurs.fr/Deuxfleurs/${{ name }}/archive/v${{ version }}.tar.gz
    sha256: 164cb58a00b1da231f881bdc61432afe925776f276c653855a4f9b980fa0cbda

build:
  skip: win
  script:
    - cd src/garage
    - export CARGO_PROFILE_RELEASE_STRIP=symbols
    - export CARGO_PROFILE_RELEASE_LTO=fat
    - cargo install --locked --no-track --bins --root ${PREFIX} --path .
    - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - make

tests:
  - script:
      - garage --help
      - garage --version
  - package_contents:
      bin:
        - garage

about:
  homepage: https://garagehq.deuxfleurs.fr
  summary: S3-compatible object store for small self-hosted geo-distributed deployments
  description: |
    Garage is an S3-compatible distributed object storage service designed for self-hosting at a small-to-medium scale.
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://git.deuxfleurs.fr/Deuxfleurs/garage
  documentation: https://garagehq.deuxfleurs.fr

extra:
  recipe-maintainers:
    - pavelzw
